stages:
  - validate
  - plan
  - apply
  - destroy
  
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    
variables:
  TF_CLI_ARGS_INIT: "-backend-config=address=${TF_VAR_address}"

before_script:
  - terraform -v
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  dependencies:
    - apply
